import styles from "../allStyles";
const btns = [
    {
        str: "",
        type: "unknown",
        text: "deg",
        txtStyle: [styles.calText, { color: "#ff773380" }],
    },
    {
        str: "sin(",
        type: "tri",
        text: "sin",
        evalLen: 12,
        textLen: 4,
        txtStyle: styles.calText,
    },
    {
        str: "cos(",
        type: "tri",
        text: "cos",
        evalLen: 12,
        textLen: 4,
        txtStyle: styles.calText,
    },
    {
        str: "tan(",
        type: "tri",
        text: "tan",
        evalLen: 12,
        textLen: 4,
        txtStyle: styles.calText,
    },
    {
        str: "",
        type: "clr",
        text: "C",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "log(",
        type: "tri",
        text: "log",
        evalLen: 12,
        textLen: 4,
        txtStyle: styles.calText,
    },
    {
        str: "ln(",
        type: "tri",
        text: "ln",
        evalLen: 11,
        textLen: 3,
        txtStyle: styles.calText,
    },
    {
        str: "asin(",
        type: "tri",
        text: "asin",
        evalLen: 13,
        textLen: 5,
        txtStyle: styles.calText,
    },
    {
        str: "acos(",
        type: "tri",
        text: "acos",
        evalLen: 13,
        textLen: 5,
        txtStyle: styles.calText,
    },
    {
        str: "atan(",
        type: "tri",
        text: "atan",
        evalLen: 13,
        textLen: 5,
        txtStyle: styles.calText,
    },
    {
        str: "sqrt(",
        type: "tri",
        text: "√",
        evalLen: 13,
        textLen: 2,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "(",
        type: "brac",
        text: "(",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: ")",
        type: "brac",
        text: ")",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "",
        type: "ere",
        text: "⌫",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "/",
        type: "sym",
        text: "÷",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "cbrt(",
        type: "tri",
        text: "∛",
        evalLen: 13,
        textLen: 2,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "7",
        type: "num",
        text: "7",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calText,
    },
    {
        str: "8",
        type: "num",
        text: "8",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calText,
    },
    {
        str: "9",
        type: "num",
        text: "9",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calText,
    },
    {
        str: "*",
        type: "sym",
        text: "×",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "**",
        type: "sym",
        text: "^",
        evalLen: 2,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "4",
        type: "num",
        text: "4",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calText,
    },
    {
        str: "5",
        type: "num",
        text: "5",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calText,
    },
    {
        str: "6",
        type: "num",
        text: "6",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calText,
    },
    {
        str: "-",
        type: "sym",
        text: "-",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "Math.PI",
        type: "num",
        text: "π",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "1",
        type: "num",
        text: "1",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calText,
    },
    {
        str: "2",
        type: "num",
        text: "2",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calText,
    },
    {
        str: "3",
        type: "num",
        text: "3",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calText,
    },
    {
        str: "+",
        type: "sym",
        text: "+",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "Math.E",
        type: "num",
        text: "e",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: ".",
        type: "point",
        text: ".",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calText,
    },
    {
        str: "0",
        type: "num",
        text: "0",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calText,
    },
    {
        str: "%",
        type: "sym",
        text: "%",
        evalLen: 1,
        textLen: 1,
        txtStyle: styles.calTextOrange,
    },
    {
        str: "=",
        type: "eql",
        text: "=",
        evalLen: 1,
        textLen: 1,
        txtStyle: [styles.calText, { fontSize: 30, fontWeight: "600" }],
    },
];
export default btns;
