const componentName = [
    {
        id: "1",
        name: "LCM",
        text: "LCM",
        path: require("../../assets/icons/LCM.png"),
    },
    {
        id: "2",
        name: "HCF",
        text: "HCF",
        path: require("../../assets/icons/HCF.png"),
    },
    {
        id: "3",
        name: "Factors",
        text: "Factors",
        path: require("../../assets/icons/bmi.png"),
    },
    {
        id: "4",
        name: "FractionSimplify",
        text: "Simplify Fraction",
        path: require("../../assets/icons/relationship.webp"),
    },
    {
        id: "5",
        name: "Multiply",
        text: "Multiply",
        path: require("../../assets/icons/multiply.png"),
    },
    {
        id: "6",
        name: "Divide",
        text: "Divide",
        path: require("../../assets/icons/devide.png"),
    },
    {
        id: "7",
        name: "SolveEqu",
        text: "Solve Equation",
        path: require("../../assets/icons/equ.png"),
    },
    {
        id: "8",
        name: "QuadraticEqu",
        text: "Quadratic Equation",
        path: require("../../assets/icons/QuadEqu.png"),
    },
    {
        id: "9",
        name: "PermutationCombination",
        text: "Permutation Combination",
        path: require("../../assets/icons/permutation.png"),
    },
    {
        id: "10",
        name: "SurfaceAreaAndVolume",
        text: "Surface Area & Volume",
        path: require("../../assets/icons/sarea.png"),
    },
    {
        id: "11",
        name: "TemperatureConverter",
        text: "Temperature Converter",
        path: require("../../assets/icons/temprature.png"),
    },
    {
        id: "12",
        name: "NumberConverter",
        text: "Number Converter",
        path: require("../../assets/icons/radix.png"),
    },
    {
        id: "13",
        name: "MassConverter",
        text: "Mass Converter",
        path: require("../../assets/icons/mass.png"),
    },
    {
        id: "14",
        name: "LengthConverter",
        text: "Length Converter",
        path: require("../../assets/icons/length.png"),
    },
    {
        id: "15",
        name: "Area",
        text: "Area Converter",
        path: require("../../assets/icons/area.png"),
    },
    {
        id: "16",
        name: "Volume",
        text: "Volume Converter",
        path: require("../../assets/icons/volume.png"),
    },
    {
        id: "17",
        name: "PowerConverter",
        text: "Power Converter",
        path: require("../../assets/icons/power.png"),
    },
    {
        id: "18",
        name: "AgeCalculator",
        text: "Age Calculator",
        path: require("../../assets/icons/date.png"),
    },
    {
        id: "19",
        name: "TimeCalculator",
        text: "Time Calculator",
        path: require("../../assets/icons/watch.png"),
    },
    {
        id: "20",
        name: "RomanNumber",
        text: "Roman Number",
        path: require("../../assets/icons/roman.png"),
    },
    {
        id: "21",
        name: "Gst",
        text: "GST",
        path: require("../../assets/icons/gst.png"),
    },
    {
        id: "22",
        name: "Discount",
        text: "Discount Calculator",
        path: require("../../assets/icons/discount.png"),
    },
    {
        id: "23",
        name: "EMICalculator",
        text: "EMI Calculator",
        path: require("../../assets/icons/emi.png"),
    },
    {
        id: "24",
        name: "MatrixMultiplication",
        text: "Matrix Multiplication",
        path: require("../../assets/icons/matrix.png"),
    },
    {
        id: "25",
        name: "Postfix",
        text: "Infix To Postfix",
        path: require("../../assets/icons/postfix.png"),
    },
    {
        id: "26",
        name: "UsefulFormula",
        text: "Useful Formulas",
        path: require("../../assets/icons/formula.png"),
    },
];
export default componentName;
