import styles from "../allStyles";
const btns = [
    {
        str: "I",
        text: "I",
        special: false,
        len: 1,
        txtStyle: styles.calText,
        btnStyle: styles.calBtn,
    },
    {
        str: "V",
        text: "V",
        special: false,
        len: 1,
        txtStyle: styles.calText,
        btnStyle: styles.calBtn,
    },
    {
        str: "X",
        text: "X",
        special: false,
        len: 1,
        txtStyle: styles.calText,
        btnStyle: styles.calBtn,
    },
    {
        str: "L",
        text: "L",
        special: false,
        len: 1,
        txtStyle: styles.calText,
        btnStyle: styles.calBtn,
    },
    {
        str: "C",
        text: "C",
        special: false,
        len: 1,
        txtStyle: styles.calText,
        btnStyle: styles.calBtn,
    },
    {
        str: "D",
        text: "D",
        special: false,
        len: 1,
        txtStyle: styles.calText,
        btnStyle: styles.calBtn,
    },
    {
        str: "M",
        text: "M",
        special: false,
        len: 1,
        txtStyle: styles.calText,
        btnStyle: styles.calBtn,
    },
    {
        str: "O",
        text: "I",
        special: true,
        len: 2,
        txtStyle: styles.romanCalText,
        btnStyle: styles.calBtn,
    },
    {
        str: "P",
        text: "V",
        special: true,
        len: 2,
        txtStyle: styles.romanCalText,
        btnStyle: styles.calBtn,
    },
    {
        str: "Q",
        text: "X",
        special: true,
        len: 2,
        txtStyle: styles.romanCalText,
        btnStyle: styles.calBtn,
    },
    {
        str: "R",
        text: "L",
        special: true,
        len: 2,
        txtStyle: styles.romanCalText,
        btnStyle: styles.calBtn,
    },
    {
        str: "S",
        text: "C",
        special: true,
        len: 2,
        txtStyle: styles.romanCalText,
        btnStyle: styles.calBtn,
    },
    {
        str: "T",
        text: "D",
        special: true,
        len: 2,
        txtStyle: styles.romanCalText,
        btnStyle: styles.calBtn,
    },
    {
        str: "U",
        text: "M",
        special: true,
        len: 2,
        txtStyle: styles.romanCalText,
        btnStyle: styles.calBtn,
    },
    {
        str: "equ",
        text: "=",
        special: false,
        len: 1,
        txtStyle: {
            fontSize: 24,
            fontWeight: "bold",
            color: "#fff",
            textAlign: "center",
        },
        btnStyle: styles.calEqual,
    },
];
export default btns;
