import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    homeMain: {
        flexDirection: "row",
        flexWrap: "wrap",
        alignItems: "center",
        justifyContent: "space-around",
        paddingVertical: 5,
    },
    homeContainer: {
        backgroundColor: "#333",
        height: "100%",
        justifyContent: "center",
        alignItems: "center",
    },
    homeBtn: {
        marginTop: 15,
        width: 100,
        height: 100,
        borderRadius: 6,
        borderColor: "#fff",
        borderWidth: 1.5,
        alignItems: "center",
        justifyContent: "center",
    },
    main: {
        flex: 1,
        backgroundColor: "#333",
    },
    container: {
        marginTop: 29,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
    },
    input: {
        height: 50,
        width: 200,
        margin: 12,
        borderWidth: 1,
        padding: 10,
        fontSize: 20,
        borderRadius: 50,
        color: "#fff",
        borderColor: "#efefef81",
        textAlign: "center",
    },
    btn: {
        marginTop: 25,
        width: 100,
        height: 33,
        borderColor: "#fff",
        fontSize: 15,
        borderWidth: 1,
        borderRadius: 33,
        justifyContent: "center",
        alignItems: "center",
    },
    btnText: {
        color: "#fff",
        textAlign: "center",
    },
    hrLine: {
        height: 2,
        backgroundColor: "#fff",
        marginVertical: 2,
        marginTop: 7,
    },
    varticleLine: {
        width: 2,
        height: 30,
        backgroundColor: "#fff",
        marginHorizontal: 4,
    },
    math: {
        alignItems: "center",
    },
    mathText: {
        fontSize: 25,
        color: "#fff",
        fontFamily: "RobotoMono_400Regular",
    },
    divideMath: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 35,
        fontFamily: "RobotoMono_400Regular",
    },
    mathContainer: {
        padding: 20,
    },
    text: {
        color: "#fff",
        fontSize: 20,
    },
    ansDiv: {
        alignItems: "center",
        padding: 20,
    },
    textStyle: {
        color: "#fff",
        fontSize: 25,
    },
    allBtns: {
        flex: 1,
        alignItems: "center",
        justifyContent: "space-around",
        padding: 20,
    },
    row: {
        flexDirection: "row",
        justifyContent: "space-around",
        width: "100%",
        height: "12.5%",
    },
    calBtn: {
        width: "20%",
        borderColor: "#fff",
        borderWidth: 1,
        borderRadius: 10,
        alignItems: "center",
        height: "100%",
        justifyContent: "center",
    },
    calText: {
        color: "#fff",
        fontSize: 25,
    },
    inputContainer: {
        alignItems: "center",
    },
    calInput: {
        height: 100,
        width: "87%",
        marginTop: 12,
        borderWidth: 1,
        padding: 10,
        fontSize: 35,
        borderRadius: 5,
        color: "#fff",
        borderColor: "#efefef81",
        textAlign: "center",
        backgroundColor: "#111",
    },
    flexRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
    },
    simplify: {
        width: "100%",
        textAlign: "center",
    },
    list: {
        width: 50,
        alignItems: "center",
        justifyContent: "center",
        marginLeft: 5,
    },
    align: {
        alignItems: "center",
    },
    dropDownStyle: {
        width: 70,
        height: 200,
        borderRadius: 10,
        backgroundColor: "#ccc",
    },
    dropDownStyleTwo: {
        width: 150,
        height: 200,
        borderRadius: 10,
        backgroundColor: "#bbb",
    },
    dropBtn: {
        width: 70,
        borderRadius: 50,
        backgroundColor: "#ccc",
    },
    dropBtnTwo: {
        width: 150,
        borderRadius: 50,
        borderColor: "#0ff",
        borderWidth: 1,
    },
});

export default styles;
